//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ziganshinakusch.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public Nullable<int> BucketId { get; set; }
        public string Items { get; set; }
        public Nullable<int> BucketId1 { get; set; }
    
        public virtual Bucket Bucket { get; set; }
    }
}
